SELECT * FROM notas_fiscais ORDER BY DATA_VENDA DESC;

SELECT YEAR(DATA_VENDA), SUM(QUANTIDADE * PRECO) AS Faturamento
FROM notas_fiscais NF INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO = INF.NUMERO
GROUP BY YEAR(DATA_VENDA)

