SELECT YEAR(A.DATA_VENDA) AS ANO_FISCAL, FLOOR(SUM(B.QUANTIDADE * B.PRECO * A.IMPOSTO)) AS IMPOSTO_ANUAL
FROM notas_fiscais A
INNER JOIN ITENS_NOTAS_FISCAIS B
ON A.NUMERO = B.NUMERO
WHERE YEAR(A.DATA_VENDA) = 2016
GROUP BY YEAR(A.DATA_VENDA);

SELECT YEAR(DATA_VENDA), FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) 
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA)
