/* SELECT PARA TER O TOTAL DE LITROS VENDIDOS EM 2016 POR SABOR */

SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO_ANALISADO, 
ROUND(SUM(INF.QUANTIDADE * INF.PRECO), 2) AS VOLUME_VENDIDO

FROM itens_notas_fiscais INF

INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO
INNER JOIN tabela_de_produtos TP ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO

WHERE YEAR(NF.DATA_VENDA) = 2016

GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
ORDER BY VOLUME_VENDIDO DESC;




/* SELECT PARA TER O TOTAL DE LITROS VENDIDOS EM 2016 */

SELECT YEAR(NF.DATA_VENDA) AS ANO_ANALISADO, 
ROUND(SUM(INF.QUANTIDADE * INF.PRECO), 2) AS VOLUME_VENDIDO

FROM itens_notas_fiscais INF

INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO
INNER JOIN tabela_de_produtos TP ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO

WHERE YEAR(NF.DATA_VENDA) = 2016

GROUP BY YEAR(NF.DATA_VENDA);



/* SELECT FINAL PARA TER O TOTAL DE LITROS VENDIDOS EM 2016 POR SABOR E A SUA PORCENTAGEM  NO VOLUME TOTAL*/

SELECT TOTAL_POR_SABOR.SABOR, TOTAL_POR_SABOR.ANO_ANALISADO, TOTAL_POR_SABOR.VOLUME_VENDIDO,
ROUND((TOTAL_POR_SABOR.VOLUME_VENDIDO / VOLUME_TOTAL.VOLUME_VENDIDO) * 100, 2) AS PORCENTAGEM
FROM 
	(SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO_ANALISADO, 
	ROUND(SUM(INF.QUANTIDADE * INF.PRECO), 2) AS VOLUME_VENDIDO
	FROM itens_notas_fiscais INF
	INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO
	INNER JOIN tabela_de_produtos TP ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
	WHERE YEAR(NF.DATA_VENDA) = 2016
	GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
	ORDER BY VOLUME_VENDIDO DESC) TOTAL_POR_SABOR
INNER JOIN
	(SELECT YEAR(NF.DATA_VENDA) AS ANO_ANALISADO, 
	ROUND(SUM(INF.QUANTIDADE * INF.PRECO), 2) AS VOLUME_VENDIDO
	FROM itens_notas_fiscais INF
	INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO
	INNER JOIN tabela_de_produtos TP ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
	WHERE YEAR(NF.DATA_VENDA) = 2016
	GROUP BY YEAR(NF.DATA_VENDA)) VOLUME_TOTAL
ON TOTAL_POR_SABOR.ANO_ANALISADO = VOLUME_TOTAL.ANO_ANALISADO
ORDER BY TOTAL_POR_SABOR.VOLUME_VENDIDO DESC;



