SELECT INF.NUMERO, YEAR(NF.DATA_VENDA), ROUND(SUM(QUANTIDADE * PRECO), 2) AS TOTAL_VENDIDO
FROM itens_notas_fiscais INF
INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO
GROUP BY INF.NUMERO, YEAR(NF.DATA_VENDA)
ORDER BY TOTAL_VENDIDO DESC;