USE VENDAS_SUCOS;

SELECT * FROM PRODUTOS;

UPDATE PRODUTOS SET PRECO_LISTA = 5 WHERE CODIGO = '1000889';

UPDATE PRODUTOS SET EMBALAGEM = 'PET', TAMANHO = '1 Litro', 
DESCRITOR = 'Sabor da Montanha - 1 Litro - Uva'
WHERE CODIGO = '1000889';

UPDATE PRODUTOS SET PRECO_LISTA = PRECO_LISTA * 1.10 WHERE SABOR = 'MARACUJÁ';

SELECT * FROM PRODUTOS WHERE SABOR = 'MARACUJÁ';

UPDATE CLIENTES 
SET ENDERECO = 'R. Jorge Emílio 23',
BAIRRO = 'SANTO AMARO',
CIDADE = 'SÃO PAULO',
ESTADO = 'SP',
CEP = '8833223'
WHERE CPF = '19290992743';

SELECT * FROM CLIENTES WHERE CPF = '19290992743';