USE VENDAS_SUCOS;

SELECT * FROM PRODUTOS;

DELETE FROM PRODUTOS
WHERE CODIGO = '1000889';


/* Exluindo itens de uma tabela usando outro BD como referência */

SELECT CODIGO FROM PRODUTOS
WHERE CODIGO NOT IN (SELECT CODIGO_DO_PRODUTO FROM SUCOS_VENDAS.TABELA_DE_PRODUTOS);

DELETE FROM PRODUTOS 
WHERE CODIGO NOT IN (SELECT CODIGO_DO_PRODUTO FROM SUCOS_VENDAS.TABELA_DE_PRODUTOS);


/* Vamos excluir as notas fiscais (Apenas o cabeçalho) cujos clientes tenham a idade menor ou igual a 18 anos */

USE VENDAS_SUCOS;

SELECT * FROM NOTAS;

SELECT A.NUMERO FROM NOTAS A
INNER JOIN CLIENTES B ON A.CPF = B.CPF
WHERE B.IDADE <= 18;

DELETE A FROM NOTAS A
INNER JOIN CLIENTES B ON A.CPF = B.CPF
WHERE B.IDADE <= 18;